name: BeatsShop
main: QuiverlyRivalry\QuiverlyRivalry
version: 1.0.1
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
author: ItsDucky

commands:
 shopui:
  description: "Access the UI for Shops!"
